Change name of logrotate rule as it may be clashing with other resource.
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/etc/cron.d/ood] is already declared at (file: /etc/puppetlabs/code/environments/staging/site/profile/manifests/base.pp, line: 68); cannot redeclare (file: /etc/puppetlabs/code/environments/staging/modules/openondemand/manifests/config.pp, line: 295) (file: /etc/puppetlabs/code/environments/staging/modules/openondemand/manifests/config.pp, line: 295, column: 3) on node ood-dev02 ...